name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (customize for your stack)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run Tests
        run: npm test

      # Step 5: Lint Code
      - name: Lint Code
        run: npm run lint

      # Step 6: Set up Go environment
      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges. Be sure to enclose this option in single quotation marks.
          go-version: '1.18'  # Customize Go version as needed
          # Path to the go.mod or go.work file (optional)
          go-version-file: 'go.mod'  # Customize this based on your project structure
          # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
          check-latest: true
          # Used to pull Go distributions from go-versions (optional, typically not required)
          token: ${{ github.token }}
          # Used to specify whether caching is needed (optional)
          cache: true

